### ISSUE TITLE
Always says "Unknown Error"

### ISSUE THREAD

**Issue by ToP09** [Moustachauve/cookie-editor#103]
I've been using this extension for a bit and when I'm trying to add cookies it says unknown error.
This time I was trying to add these cookies to grammarly.com

`[
{
"domain": ".grammarly.com",
"expirationDate": 1660944638,
"hostOnly": false,
"httpOnly": false,
"name": "_gcl_au",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1.1.1737722812.1653168638"
},
{
"domain": ".grammarly.com",
"expirationDate": 1654093249,
"hostOnly": false,
"httpOnly": false,
"name": "isGrammarlyUser",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "true"
},
{
"domain": ".grammarly.com",
"expirationDate": 1685024448.990062,
"hostOnly": false,
"httpOnly": true,
"name": "grauth",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "AABKwdOQMyCyG3VQJdjelZNYieOUJNqrbn0kKuQgvGvD4F3tftjnfCuypz01flJdsmU4NcD8bpZndyj6"
},
{
"domain": ".grammarly.com",
"expirationDate": 1653492052.079836,
"hostOnly": false,
"httpOnly": true,
"name": "redirect_location",
"path": "/",
"sameSite": null,
"secure": true,
"session": false,
"storeId": null,
"value": "eyJ0eXBlIjoiIiwibG9jYXRpb24iOiJodHRwczovL2FwcC5ncmFtbWFybHkuY29tLyJ9"
},
{
"domain": ".grammarly.com",
"expirationDate": 1716560452,
"hostOnly": false,
"httpOnly": false,
"name": "_ga_CBK9K2ZWWE",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "GS1.1.1653488442.5.1.1653488452.50"
},
{
"domain": ".grammarly.com",
"expirationDate": 1653574842,
"hostOnly": false,
"httpOnly": false,
"name": "_gid",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "GA1.2.1070794741.1653488443"
},
{
"domain": ".grammarly.com",
"expirationDate": 1676816445,
"hostOnly": false,
"httpOnly": false,
"name": "_cc_id",
"path": "/",
"sameSite": "lax",
"secure": false,
"session": false,
"storeId": null,
"value": "e1d679ea77b40267ddc85becde001f1"
},
{
"domain": ".grammarly.com",
"expirationDate": 1685024455.997693,
"hostOnly": false,
"httpOnly": false,
"name": "experiment_groups",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "fsrw_in_sidebar_allusers_enabled|extension_new_rich_text_fields_enabled|gdocs_for_chrome_enabled|officeaddin_outcomes_ui_exp5_enabled1|gb_tone_detector_onboarding_flow_enabled|completions_beta_enabled|premium_ungating_renewal_notification_enabled|kaza_security_hub_enabled|quarantine_messages_enabled|small_hover_menus_existing_enabled|gb_snippets_csv_upload_enabled|grammarly_web_ukraine_logo_dapi_enabled|officeaddin_upgrade_state_exp2_enabled1|gb_in_editor_premium_Test1|gb_analytics_mvp_phase_one_enabled|gb_rbac_new_members_ui_enabled|ipm_extension_release_test_1|snippets_in_ws_gate_enabled|extension_assistant_bundles_all_enabled|gb_analytics_group_filters_enabled|officeaddin_proofit_exp3_enabled|gdocs_for_all_firefox_enabled|gb_snippets_cycle_one_enabled|shared_workspaces_enabled|gb_analytics_mvp_phase_one_30_day_enabled|auto_complete_correct_safari_enabled|fluid_gdocs_rollout_enabled|officeaddin_ue_exp3_enabled|officeaddin_upgrade_state_exp1_enabled1|safari_migration_inline_disabled_enabled|completions_release_enabled1|fsrw_in_assistant_all_enabled|autocorrect_new_ui_v3|emogenie_beta_enabled|apply_formatting_all_enabled|shadow_dom_chrome_enabled|extension_assistant_experiment_all_enabled|gdocs_for_all_safari_enabled|extension_assistant_all_enabled|safari_migration_backup_notif1_enabled|auto_complete_correct_edge_enabled|takeaways_premium_enabled|realtime_proofit_external_rollout_enabled|safari_migration_popup_editor_disabled_enabled|extension_check_manakin_v2_experiment_enabled|safari_migration_inline_warning_enabled|llama_beta_managed_test_1|gdocs_new_mapping_enabled|gb_expanded_analytics_enabled|officeaddin_perf_exp3_enabled|officeaddin_muted_alerts_exp2_enabled1"
},
{
"domain": ".grammarly.com",
"expirationDate": 1968787838,
"hostOnly": false,
"httpOnly": false,
"name": "ga_clientId",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1362229555.1653168639"
},
{
"domain": ".grammarly.com",
"expirationDate": 1685024446,
"hostOnly": false,
"httpOnly": false,
"name": "_clck",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "14n1h9t|1|f1r|0"
},
{
"domain": ".grammarly.com",
"expirationDate": 1685024448.990193,
"hostOnly": false,
"httpOnly": false,
"name": "csrf-token",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "AABKwftVkTUjxkZwNdCxstweT0h2jgqQf+KzDA"
},
{
"domain": ".grammarly.com",
"expirationDate": 1653574846,
"hostOnly": false,
"httpOnly": false,
"name": "_clsk",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1y00gf0|1653488446536|1|0|f.clarity.ms/collect"
},
{
"domain": ".grammarly.com",
"expirationDate": 1716560443,
"hostOnly": false,
"httpOnly": false,
"name": "_ga",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "GA1.1.1362229555.1653168639"
},
{
"domain": ".grammarly.com",
"expirationDate": 1653488503,
"hostOnly": false,
"httpOnly": false,
"name": "_gat",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "1"
},
{
"domain": ".grammarly.com",
"expirationDate": 1653574843,
"hostOnly": false,
"httpOnly": false,
"name": "_uetsid",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "dcd30150dc3511ec89d8ef5799c10c3d"
},
{
"domain": ".grammarly.com",
"expirationDate": 1687184443,
"hostOnly": false,
"httpOnly": false,
"name": "_uetvid",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "4461e770d94d11ec9d66e7c457505a6c"
},
{
"domain": ".grammarly.com",
"expirationDate": 1653492052.080029,
"hostOnly": false,
"httpOnly": false,
"name": "browser_info",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "CHROME:101:COMPUTER:SUPPORTED:FREEMIUM:WINDOWS_10:WINDOWS"
},
{
"domain": ".grammarly.com",
"expirationDate": 1653596452.079961,
"hostOnly": false,
"httpOnly": false,
"name": "funnelType",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "free"
},
{
"domain": ".grammarly.com",
"expirationDate": 1968528632.716933,
"hostOnly": false,
"httpOnly": false,
"name": "gnar_containerId",
"path": "/",
"sameSite": null,
"secure": false,
"session": false,
"storeId": null,
"value": "mstz73s7bcs00202"
},
{
"domain": ".grammarly.com",
"expirationDate": 1654093246,
"hostOnly": false,
"httpOnly": false,
"name": "panoramaId",
"path": "/",
"sameSite": "lax",
"secure": false,
"session": false,
"storeId": null,
"value": "58529db859aa4ec92d1f7786b1c14945a702451eba28f444b404f58cf4e7992f"
},
{
"domain": ".grammarly.com",
"expirationDate": 1654093246,
"hostOnly": false,
"httpOnly": false,
"name": "panoramaId_expiry",
"path": "/",
"sameSite": "lax",
"secure": false,
"session": false,
"storeId": null,
"value": "1654093245694"
},
{
"domain": ".grammarly.com",
"expirationDate": 1968528702.318866,
"hostOnly": false,
"httpOnly": true,
"name": "tdi",
"path": "/",
"sameSite": "no_restriction",
"secure": true,
"session": false,
"storeId": null,
"value": "apcfd1y6beak10oap"
}
]`

I've also tried to remove the "." before "grammarly.com" but still didn't work..

**Comment by HeartsofCourse** [comment]
I think there was an update or something that broke it. I used some cookies for a website a couple days ago, and they worked flawlessly. Today I went to the website and I wasn't signed into it, so I tried putting the cookies in again and it gave this error. It can't be the cookies that are the problem, it must be on Cookie Editor's end

**Comment by Doni108108** [comment]
> I've been using this extension for a bit and when I'm trying to add cookies it says unknown error.
> This time I was trying to add these cookies to grammarly.com
> 
> `[
> {
> "domain": ".grammarly.com",
> "expirationDate": 1660944638,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_gcl_au",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1.1.1737722812.1653168638"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1654093249,
> "hostOnly": false,
> "httpOnly": false,
> "name": "isGrammarlyUser",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "true"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024448.990062,
> "hostOnly": false,
> "httpOnly": true,
> "name": "grauth",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "AABKwdOQMyCyG3VQJdjelZNYieOUJNqrbn0kKuQgvGvD4F3tftjnfCuypz01flJdsmU4NcD8bpZndyj6"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653492052.079836,
> "hostOnly": false,
> "httpOnly": true,
> "name": "redirect_location",
> "path": "/",
> "sameSite": null,
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "eyJ0eXBlIjoiIiwibG9jYXRpb24iOiJodHRwczovL2FwcC5ncmFtbWFybHkuY29tLyJ9"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1716560452,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_ga_CBK9K2ZWWE",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "GS1.1.1653488442.5.1.1653488452.50"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653574842,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_gid",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "GA1.2.1070794741.1653488443"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1676816445,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_cc_id",
> "path": "/",
> "sameSite": "lax",
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "e1d679ea77b40267ddc85becde001f1"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024455.997693,
> "hostOnly": false,
> "httpOnly": false,
> "name": "experiment_groups",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "fsrw_in_sidebar_allusers_enabled|extension_new_rich_text_fields_enabled|gdocs_for_chrome_enabled|officeaddin_outcomes_ui_exp5_enabled1|gb_tone_detector_onboarding_flow_enabled|completions_beta_enabled|premium_ungating_renewal_notification_enabled|kaza_security_hub_enabled|quarantine_messages_enabled|small_hover_menus_existing_enabled|gb_snippets_csv_upload_enabled|grammarly_web_ukraine_logo_dapi_enabled|officeaddin_upgrade_state_exp2_enabled1|gb_in_editor_premium_Test1|gb_analytics_mvp_phase_one_enabled|gb_rbac_new_members_ui_enabled|ipm_extension_release_test_1|snippets_in_ws_gate_enabled|extension_assistant_bundles_all_enabled|gb_analytics_group_filters_enabled|officeaddin_proofit_exp3_enabled|gdocs_for_all_firefox_enabled|gb_snippets_cycle_one_enabled|shared_workspaces_enabled|gb_analytics_mvp_phase_one_30_day_enabled|auto_complete_correct_safari_enabled|fluid_gdocs_rollout_enabled|officeaddin_ue_exp3_enabled|officeaddin_upgrade_state_exp1_enabled1|safari_migration_inline_disabled_enabled|completions_release_enabled1|fsrw_in_assistant_all_enabled|autocorrect_new_ui_v3|emogenie_beta_enabled|apply_formatting_all_enabled|shadow_dom_chrome_enabled|extension_assistant_experiment_all_enabled|gdocs_for_all_safari_enabled|extension_assistant_all_enabled|safari_migration_backup_notif1_enabled|auto_complete_correct_edge_enabled|takeaways_premium_enabled|realtime_proofit_external_rollout_enabled|safari_migration_popup_editor_disabled_enabled|extension_check_manakin_v2_experiment_enabled|safari_migration_inline_warning_enabled|llama_beta_managed_test_1|gdocs_new_mapping_enabled|gb_expanded_analytics_enabled|officeaddin_perf_exp3_enabled|officeaddin_muted_alerts_exp2_enabled1"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1968787838,
> "hostOnly": false,
> "httpOnly": false,
> "name": "ga_clientId",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1362229555.1653168639"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024446,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_clck",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "14n1h9t|1|f1r|0"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024448.990193,
> "hostOnly": false,
> "httpOnly": false,
> "name": "csrf-token",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "AABKwftVkTUjxkZwNdCxstweT0h2jgqQf+KzDA"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653574846,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_clsk",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1y00gf0|1653488446536|1|0|f.clarity.ms/collect"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1716560443,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_ga",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "GA1.1.1362229555.1653168639"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653488503,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_gat",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653574843,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_uetsid",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "dcd30150dc3511ec89d8ef5799c10c3d"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1687184443,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_uetvid",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "4461e770d94d11ec9d66e7c457505a6c"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653492052.080029,
> "hostOnly": false,
> "httpOnly": false,
> "name": "browser_info",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "CHROME:101:COMPUTER:SUPPORTED:FREEMIUM:WINDOWS_10:WINDOWS"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653596452.079961,
> "hostOnly": false,
> "httpOnly": false,
> "name": "funnelType",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "free"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1968528632.716933,
> "hostOnly": false,
> "httpOnly": false,
> "name": "gnar_containerId",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "mstz73s7bcs00202"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1654093246,
> "hostOnly": false,
> "httpOnly": false,
> "name": "panoramaId",
> "path": "/",
> "sameSite": "lax",
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "58529db859aa4ec92d1f7786b1c14945a702451eba28f444b404f58cf4e7992f"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1654093246,
> "hostOnly": false,
> "httpOnly": false,
> "name": "panoramaId_expiry",
> "path": "/",
> "sameSite": "lax",
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1654093245694"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1968528702.318866,
> "hostOnly": false,
> "httpOnly": true,
> "name": "tdi",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "apcfd1y6beak10oap"
> }
> ]`
> 
> I've also tried to remove the "." before "grammarly.com" but still didn't work..

**Comment by Doni108108** [comment]
> I've been using this extension for a bit and when I'm trying to add cookies it says unknown error.
> This time I was trying to add these cookies to grammarly.com
> 
> `[
> {
> "domain": ".grammarly.com",
> "expirationDate": 1660944638,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_gcl_au",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1.1.1737722812.1653168638"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1654093249,
> "hostOnly": false,
> "httpOnly": false,
> "name": "isGrammarlyUser",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "true"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024448.990062,
> "hostOnly": false,
> "httpOnly": true,
> "name": "grauth",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "AABKwdOQMyCyG3VQJdjelZNYieOUJNqrbn0kKuQgvGvD4F3tftjnfCuypz01flJdsmU4NcD8bpZndyj6"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653492052.079836,
> "hostOnly": false,
> "httpOnly": true,
> "name": "redirect_location",
> "path": "/",
> "sameSite": null,
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "eyJ0eXBlIjoiIiwibG9jYXRpb24iOiJodHRwczovL2FwcC5ncmFtbWFybHkuY29tLyJ9"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1716560452,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_ga_CBK9K2ZWWE",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "GS1.1.1653488442.5.1.1653488452.50"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653574842,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_gid",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "GA1.2.1070794741.1653488443"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1676816445,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_cc_id",
> "path": "/",
> "sameSite": "lax",
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "e1d679ea77b40267ddc85becde001f1"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024455.997693,
> "hostOnly": false,
> "httpOnly": false,
> "name": "experiment_groups",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "fsrw_in_sidebar_allusers_enabled|extension_new_rich_text_fields_enabled|gdocs_for_chrome_enabled|officeaddin_outcomes_ui_exp5_enabled1|gb_tone_detector_onboarding_flow_enabled|completions_beta_enabled|premium_ungating_renewal_notification_enabled|kaza_security_hub_enabled|quarantine_messages_enabled|small_hover_menus_existing_enabled|gb_snippets_csv_upload_enabled|grammarly_web_ukraine_logo_dapi_enabled|officeaddin_upgrade_state_exp2_enabled1|gb_in_editor_premium_Test1|gb_analytics_mvp_phase_one_enabled|gb_rbac_new_members_ui_enabled|ipm_extension_release_test_1|snippets_in_ws_gate_enabled|extension_assistant_bundles_all_enabled|gb_analytics_group_filters_enabled|officeaddin_proofit_exp3_enabled|gdocs_for_all_firefox_enabled|gb_snippets_cycle_one_enabled|shared_workspaces_enabled|gb_analytics_mvp_phase_one_30_day_enabled|auto_complete_correct_safari_enabled|fluid_gdocs_rollout_enabled|officeaddin_ue_exp3_enabled|officeaddin_upgrade_state_exp1_enabled1|safari_migration_inline_disabled_enabled|completions_release_enabled1|fsrw_in_assistant_all_enabled|autocorrect_new_ui_v3|emogenie_beta_enabled|apply_formatting_all_enabled|shadow_dom_chrome_enabled|extension_assistant_experiment_all_enabled|gdocs_for_all_safari_enabled|extension_assistant_all_enabled|safari_migration_backup_notif1_enabled|auto_complete_correct_edge_enabled|takeaways_premium_enabled|realtime_proofit_external_rollout_enabled|safari_migration_popup_editor_disabled_enabled|extension_check_manakin_v2_experiment_enabled|safari_migration_inline_warning_enabled|llama_beta_managed_test_1|gdocs_new_mapping_enabled|gb_expanded_analytics_enabled|officeaddin_perf_exp3_enabled|officeaddin_muted_alerts_exp2_enabled1"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1968787838,
> "hostOnly": false,
> "httpOnly": false,
> "name": "ga_clientId",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1362229555.1653168639"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024446,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_clck",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "14n1h9t|1|f1r|0"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1685024448.990193,
> "hostOnly": false,
> "httpOnly": false,
> "name": "csrf-token",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "AABKwftVkTUjxkZwNdCxstweT0h2jgqQf+KzDA"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653574846,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_clsk",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1y00gf0|1653488446536|1|0|f.clarity.ms/collect"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1716560443,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_ga",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "GA1.1.1362229555.1653168639"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653488503,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_gat",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653574843,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_uetsid",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "dcd30150dc3511ec89d8ef5799c10c3d"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1687184443,
> "hostOnly": false,
> "httpOnly": false,
> "name": "_uetvid",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "4461e770d94d11ec9d66e7c457505a6c"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653492052.080029,
> "hostOnly": false,
> "httpOnly": false,
> "name": "browser_info",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "CHROME:101:COMPUTER:SUPPORTED:FREEMIUM:WINDOWS_10:WINDOWS"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1653596452.079961,
> "hostOnly": false,
> "httpOnly": false,
> "name": "funnelType",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "free"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1968528632.716933,
> "hostOnly": false,
> "httpOnly": false,
> "name": "gnar_containerId",
> "path": "/",
> "sameSite": null,
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "mstz73s7bcs00202"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1654093246,
> "hostOnly": false,
> "httpOnly": false,
> "name": "panoramaId",
> "path": "/",
> "sameSite": "lax",
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "58529db859aa4ec92d1f7786b1c14945a702451eba28f444b404f58cf4e7992f"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1654093246,
> "hostOnly": false,
> "httpOnly": false,
> "name": "panoramaId_expiry",
> "path": "/",
> "sameSite": "lax",
> "secure": false,
> "session": false,
> "storeId": null,
> "value": "1654093245694"
> },
> {
> "domain": ".grammarly.com",
> "expirationDate": 1968528702.318866,
> "hostOnly": false,
> "httpOnly": true,
> "name": "tdi",
> "path": "/",
> "sameSite": "no_restriction",
> "secure": true,
> "session": false,
> "storeId": null,
> "value": "apcfd1y6beak10oap"
> }
> ]`
> 
> I've also tried to remove the "." before "grammarly.com" but still didn't work..

>
