### ISSUE TITLE
after cookie was created succesfully, i get: this page does not have any cookie

### ISSUE THREAD

**Issue by csengh** [Moustachauve/cookie-editor#106]
as the title says, I delete all cookie on site, then add cookie with json and  I get: "cookie was created succesfully" message, but in cookie editor I still have:  "this page does not have any cookie"
what means this, where is the created cookie?

**Comment by Moustachauve** [comment]
This version is now available on the Chrome Web Store! It will be available soon but is pending review for Firefox, Opera, Edge and Safari.

**Comment by csengh** [comment]
unfortunately I use Firefox.

**Comment by Moustachauve** [comment]
The update is now also available for Firefox and Edge

**Comment by csengh** [comment]
thank's your fast help :)
