### ISSUE TITLE
Netscape format always set subdomain attribute to `TRUE`

### ISSUE THREAD

**Issue by elonzh** [Moustachauve/cookie-editor#110]
According to [the format spec](https://curl.se/docs/http-cookies.html#:~:text=boolean%20FALSE%20%2D%20include%20subdomains)

The second attribute indicate cookie includes subdomains or not, this is not always  `TRUE` in the real world for example, python will check this attribute and raise an exception when it is wrong.

```python
# http.cookiejar.MozillaCookieJar._really_load
domain, domain_specified, path, secure, expires, name, value = \
                        line.split("\t")
                secure = (secure == "TRUE")
                domain_specified = (domain_specified == "TRUE")
                if name == "":
                    # cookies.txt regards 'Set-Cookie: foo' as a cookie
                    # with no name, whereas http.cookiejar regards it as a
                    # cookie with no value.
                    name = value
                    value = None

                initial_dot = domain.startswith(".")
                assert domain_specified == initial_dot
```

Based on the python logic, the fix is easy, set it to "TRUE" when the domain starts with "."  or set "FALSE" if not.

https://github.com/Moustachauve/cookie-editor/blob/master/interface/popup/cookie-list.js#L595

**Comment by Moustachauve** [comment]
This is now fixed in version 1.12.0! This version is slowly rolling out for all browsers.
