### ISSUE TITLE
IOs updates?

### ISSUE THREAD

**Issue by binisalihi** [Moustachauve/cookie-editor#111]
I wanted to download it for IOs but its only in the version 10.13 so I was wondering if there are gonna be new updates to the app there or no?

**Comment by Moustachauve** [comment]
Hello, the iOS version of my extension is not yet available. There are only clones for now. Never pay for Cookie-Editor.

**Comment by binisalihi** [comment]
Ok thank you but is there ever going too be one or in the future?

**Comment by Moustachauve** [comment]
Yes, I'm working on it but there is currently an issue that I am trying to fix with Apple about this. I'll update this issue once I have more informations.

**Comment by Moustachauve** [comment]
Cookie-Editor is now available in the App store for Safari on iOS! https://apps.apple.com/app/apple-store/id6446215341?pt=126143671&ct=github&mt=8
