### ISSUE TITLE
Cookies-editor on Safari iPhone iOS 16.4.1

### ISSUE THREAD

**Issue by Eng-RSMY** [Moustachauve/cookie-editor#112]
After installing it on iPhone, it asks to turn cookies-editor's safari extension in settings. Even though it is ON but the screen remains the 
same, which gives the option to import or export or edit cookies

![cookies editor_iOS 16 4 1](https://user-images.githubusercontent.com/31055556/230789032-199fcf3e-920b-4a4f-a4a2-65147b6533d1.jpeg)

**Comment by Moustachauve** [comment]
Hello, After turning it on, you don't need to access the app. When you use Safari, you should notice the Cookie-Editor icon in your Safari menu. You can tap it to see and edit your cookies from there.

**Comment by Eng-RSMY** [comment]
Thanks for your kind response.. but still I don't see Cookies-Editor icon in the Safari menu

**Comment by Moustachauve** [comment]
Here is how to access it:
![image](https://user-images.githubusercontent.com/2206577/232667972-f4e8a7de-0914-4ac9-b86b-350d31ac089f.png)

If you don't see it, what version of iOS do you have? Which device?

**Comment by Eng-RSMY** [comment]
Thanks a lot, and much appreciated for your kind support.
