### ISSUE TITLE
[Error on Safari 15.4 and Xcode 13.4.1 (13F100)] The service_worker script failed to load due to an error.

### ISSUE THREAD

**Issue by DragonLeo188** [Moustachauve/cookie-editor#113]
When I install _cookie-editor_ extension directly from _App Store_, I get error "**The service_worker script failed to load due to an error.**"

When I build and run the code on _Xcode Version 13.4.1 (13F100)_, Safari quit after I uninstall the extension. 

Safari Version: **15.4 (17613.1.17.1.6)**
Xcode Version: **13.4.1 (13F100**
MacOS Version: **macOS Monterey version 12.3**

Is it possible to fix these errors ?

**Comment by Moustachauve** [comment]
I've only tried to build it with xcode 14, maybe you could try that?
