### ISSUE TITLE
Configuring the extension - disabling netscape export option

### ISSUE THREAD

**Issue by azerafati** [Moustachauve/cookie-editor#114]
I've always used this extension and it is very nice and handy but in the last update I have this extra click when choosing `Export` to select between Json and Netscape which is very annoying for me. It's only an extra click but I never used the netscape version, So I wish there was a way for me to disable it altogether and save that constant extra click.

![image](https://user-images.githubusercontent.com/6585609/232727739-02da1880-47b9-4d02-aec3-0a2cea312264.png)

**Comment by azerafati** [comment]
Thinking more, maybe a better solution would be to have keyboard shortcuts in the extension.

**Comment by keerthirar** [comment]
I am need an option to set default export option (Say. JSON)

**Comment by Moustachauve** [comment]
I'm planning on adding a configuration page in the next update where this could be set as an option.

**Comment by Moustachauve** [comment]
This is now fixed in version 1.12.0! This version is slowly rolling out for all browsers.
