### ISSUE TITLE
Not actually available on Firefox for Android

### ISSUE THREAD

**Issue by SteegHobland** [Moustachauve/cookie-editor#115]
The Cookie-editor site says that it's available on Firefox for Android, but when I try to get it, the Mozilla page says that it's not available on Firefox for Android.

**Comment by Moustachauve** [comment]
It is available, but it is not simple anymore. You need to use the Firefox nightly app version and follow the steps described in this article:

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by SteegHobland** [comment]
Oh, looks needlessly complicated. Thanks for the quick response!
