### ISSUE TITLE
[FEATURE REQUEST] Import/Export format: cookie header string

### ISSUE THREAD

**Issue by evilsh3ll** [Moustachauve/cookie-editor#116]
Hello, 
could you add the import/export option "standard cookie header string"? 
So "key1=value1; key2=value2 ..."
There is another foss chrome addon (Cookiedough) that implemented this feature. I often use it, I hope you can add it to your extension.

**Comment by Moustachauve** [comment]
I'm planning on adding this in the next version.

**Comment by evilsh3ll** [comment]
is there any ETA?
thanks

**Comment by Moustachauve** [comment]
I don't have a strict ETA but this is the next part that I'm working on this week. It is also one of the last thing missing for me to launch the next version of the extension (It's a big update! Lots of refactoring internally).

**Comment by Moustachauve** [comment]
This is now fixed in version 1.12.0! This version is slowly rolling out for all browsers.
