### ISSUE TITLE
The code is added to chrome extension after pulling down build, and the plug-in cannot be used normally. When I delete the following error, please help me.

### ISSUE THREAD

**Issue by mhoudun** [Moustachauve/cookie-editor#118]
![image](https://github.com/Moustachauve/cookie-editor/assets/28923228/6e451211-f4d7-4bec-9158-95845cabcc28)
![image](https://github.com/Moustachauve/cookie-editor/assets/28923228/b57b5874-b7dc-4d62-b523-df1235e67d8c)

**Comment by Moustachauve** [comment]
It seems you are using an unreleased pre-stable build of Cookie-Editor. It is possible that there are some bugs that are not fixed yet. Did you allow all permissions required for Cookie-Editor?
