### ISSUE TITLE
cookie editor for firefox mobile version 

### ISSUE THREAD

**Issue by harshG775** [Moustachauve/cookie-editor#120]
How to add cookie editor in firefox mobile version

**Comment by harshG775** [comment]
//

**Comment by Moustachauve** [comment]
It is possible, but it is not simple anymore. You need to use the Firefox nightly app version and follow the steps described in this article:

https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
