### ISSUE TITLE
Can’t load extension on safari

### ISSUE THREAD

**Issue by djahojak** [Moustachauve/cookie-editor#121]
I installed Cookie-Editor but when i try to turn it on i get this message (Cookie-Editor extension cannot be loaded contact the developer for support)
![A4BFDD49-36DB-48B2-9310-1ACE72CA2CF7](https://github.com/Moustachauve/cookie-editor/assets/138735366/89c58ed2-708a-4392-abab-368f0adb9e30)

**Comment by Moustachauve** [comment]
Which iOS version are you on?

**Comment by PeZoi** [comment]
15.3.1

**Comment by Moustachauve** [comment]
Could you check if you still have the issue with the latest version of the extension please?
