### ISSUE TITLE
Cookies that cannot be displayed on the page

### ISSUE THREAD

**Issue by yinyutaoyyt** [Moustachauve/cookie-editor#135]
![image](https://github.com/Moustachauve/cookie-editor/assets/38715372/c900807a-707a-4870-8dc8-ee43d1be4011)
Cookies that cannot be displayed on the page

**Comment by Moustachauve** [comment]
Hello, what browser did you have this issue? Is it on all sites?

**Comment by yinyutaoyyt** [comment]
I use Google Chrome, I know why
This problem will occur if you authorize specific websites. Cookies will not be displayed for authorized and unauthorized websites.
Authorize all websites to display

**Comment by yinyutaoyyt** [comment]
> 您好，请问您是用什么浏览器出现这个问题的？所有网站上都有吗？

I use Google Chrome, I know why
This problem will occur if you authorize specific websites. Cookies will not be displayed for authorized and unauthorized websites.
Authorize all websites to display

**Comment by Moustachauve** [comment]
Ah yes, sorry about that. This is a known issue currently on Google Chrome only. I am still investigating how this can be fixed.

**Comment by kupal234** [comment]
not show 

![Image](https://github.com/user-attachments/assets/b4fc316d-f39a-4f35-b47c-2552a351de77)
