### ISSUE TITLE
Cookie Import not working

### ISSUE THREAD

**Issue by 29ayush** [Moustachauve/cookie-editor#14]
I paste the cookies and click on import but nothing happens.

When I paste wrong json it prompts unable to parse json.

but when I paste correct json nothing happens

**Comment by Moustachauve** [comment]
Thanks for the report, @29ayush. Would you be able to provide some additional data like the website you were on and an example/sample of the cookies you were trying to import? Just to make sure, you can only import cookies for the website you are currently on the active tab.

Also, please be careful to make sure that if you provide me with an example, that there is no personal data in there.

**Comment by 29ayush** [comment]
Actually I was using Firefox 61, at the time I opened the above bug.
After I updated my firefox to firefox 66 it's working properly.

**Comment by Moustachauve** [comment]
Thank you for your input, I will be doing some tests to see if it can be fixed for older versions of firefox. At least I am happy that you could work around it
