### ISSUE TITLE
suggestions for better UX: no animations, buttons on top, optional ads

### ISSUE THREAD

**Issue by WAZAAAAA0** [Moustachauve/cookie-editor#141]
Been using Cookie-Editor for a while because it's the quickest way to import/export cookies so far, but I feel like the time needed to navigate the menus could be reduced further.

1. Remove all animations and transitions.
They waste time for no gain and go against the idea of having a *quick* cookie editor. If outright removing them sounds too extreme, make them optional. I modded for myself the js and css animations out of the extension as a test, and it does [feel snappier](https://files.catbox.moe/ksaxp6.zip).

2. Move the `Add - Delete All - Import - Export - Cancel` buttons to the top.
Currently you need to sort of "chase the buttons around" because the various windows have different (sometimes variable) heights. This problem is made worse by the presence of the aforementioned animations that slow things down. Moving the buttons to the top would solve all that. It would also have the additional benefit of putting the essential buttons closer to the extension icon that people click on from the browser toolbar. And as a further but very minor advantage, it would make Tab-navigation require less Tab inputs to reach the important buttons.

3. Make the affiliate ads optional.
Leave them ON by default since they're non-intrusive, with an OFF toggle buried in the settings to hide them completely. This way most people will still keep them ON (because honestly most people don't touch the defaults), and those who really can't stand them will disable them, and hopefully leave less 1 star reviews lol.

**Comment by Moustachauve** [comment]
I think 1 and 2 are good valid point and shouldn't be too hard to implement, so I'll look into it in the future.

I'm not sure yet about 3, I'll experiment with it!

**Comment by WAZAAAAA0** [comment]
Just tested the changes that implement #​1 and #​3, and they simply work as expected 👌

Removing the animations has the added unexpected benefit of fixing an obscure bug that can be reproduced like this:
1. have some pre-existing cookie on any site
2. click `Delete All` and `Import` in succession ***extremely*** fast (Left Click on Delete All -> Tab -> Space makes it easier to reproduce)
3. you'll find yourself in a situation where only the `Cancel` and `Import` buttons exist but there's no text field to write anything, forcing you to `Cancel`

That would leave #​2 left, but maybe I shouldn't have merged these many issues into a single one in the first place, feel free to close this whenever you want

**Comment by Moustachauve** [comment]
I'd like to implement the option to have the bar at the top, I should be able to try it out soon :)

**Comment by Moustachauve** [comment]
The option to display the button bar to the top has been implemented and will be in the next update :)

Can you open a new separate issue for the display bug please?
