### ISSUE TITLE
Cookie-editor

### ISSUE THREAD

**Issue by Hanuman65** [Moustachauve/cookie-editor#152]
When I open the cookie editor to use it, a message is being shown again and again, even if I have given Shari settings or cookies permission, the same message is still being shown as in the following screen.
![Screenshot_2024-01-02-18-49-28-068_com lemurbrowser exts](https://github.com/Moustachauve/cookie-editor/assets/80748510/4f5a7825-62f4-4b46-9ef1-88b66f7e1684)

**Comment by Moustachauve** [comment]
What browser are you using?

**Comment by Broskiss** [comment]
> What browser are you using?

He using kiwi browser I guess that's my problem too that's why I'm hire

**Comment by Moustachauve** [comment]
Kiwi browser isn't supported. See #132 for context and for a workaround
