### ISSUE TITLE
Extension doesn't work properly in vivaldi browser

### ISSUE THREAD

**Issue by Hazem42** [Moustachauve/cookie-editor#153]
![Screenshot (6)](https://github.com/Moustachauve/cookie-editor/assets/89294365/74b63b45-1bd6-48ce-98fe-961459e29610)
windows 11 pro 23H2

**Comment by Moustachauve** [comment]
@Hazem42 I can't reproduce the issue you're having. How do you get the small popup? I only get a full sidebar. I'm on a clean install of vivaldi 6.5.3206.63 (Stable channel) (64-bit)

**Comment by Hazem42** [comment]
Works well now, probably was a Vivaldi issue, and got fixed after an update
