### ISSUE TITLE
I want to use cookies with durations

### ISSUE THREAD

**Issue by risrismulyadi** [Moustachauve/cookie-editor#154]
I want to use cookies with durations such as 1 week, 1 month, and 1 year, how can I do that?

**Comment by Moustachauve** [comment]
You can set the expiration date one week in the future.

**Comment by risrismulyadi** [comment]
tell me how to do that please?

**Comment by risrismulyadi** [comment]
my english is broken sry

**Comment by Moustachauve** [comment]
When editing a cookie, open the advanced form, make sure the "session" checkbox is not checked and set the expiration date 1 week or 1 month or more in the future.

![image](https://github.com/Moustachauve/cookie-editor/assets/2206577/5dd8b669-b1b4-49a5-b9b4-fe7bd39b2cc4)
