### ISSUE TITLE
cookies.lib

### ISSUE THREAD

**Issue by PmPPolska** [Moustachauve/cookie-editor#156]
[{"domain":".github.com","expirationDate":1736332948.12825,"hostOnly":false,"httpOnly":false,"name":"_octo","path":"/","sameSite":"lax","secure":true,"session":false,"storeId":"0","value":"GH1.1.165666710.1704710549"},{"domain":".github.com/brl33","expirationDate":1736332948.128364,"hostOnly":false,"httpOnly":true,"name":"logged_in","path":"/","sameSite":"lax","secure":true,"session":false,"storeId":"0","value":"no"},{"domain":".github.com","hostOnly":false,"httpOnly":false,"name":"preferred_color_mode","path":"/","sameSite":"lax","secure":true,"session":true,"storeId":"0","value":"light"},{"domain":".github.com","hostOnly":false,"httpOnly":false,"name":"tz","path":"/","sameSite":"lax","secure":true,"session":true,"storeId":"0","value":"Europe%2FWarsaw"},{"domain":"docs.github.com","expirationDate":1736247087,"hostOnly":true,"httpOnly":false,"name":"_docs-events","path":"/","sameSite":"strict","secure":true,"session":false,"storeId":"0","value":"ae154cd3-f060-4a8c-a265-f840678f66bc"}]

**Comment by Moustachauve** [comment]
Do not use this information. It could cause you to lose your accounts.
