### ISSUE TITLE
Cokie editor

### ISSUE THREAD

**Issue by Hbrgmryt** [Moustachauve/cookie-editor#159]
When i try to add any cokie editor extension to chrome then the button is not show why?
This is doing for me pls tell me
![Screenshot_2024-01-23-21-12-35](https://github.com/Moustachauve/cookie-editor/assets/157505032/9b017961-cae0-49b4-b9e2-de28050eda72)

**Comment by Moustachauve** [comment]
Is this Kiwi browser? It's not supported. See #132
