### ISSUE TITLE
Abundant Space on Interface

### ISSUE THREAD

**Issue by Riajyuu** [Moustachauve/cookie-editor#16]
![image](https://user-images.githubusercontent.com/16912240/56717702-d4c19d00-676f-11e9-9be3-20ec4ab21c93.png)

This happens when you expand any item and collapse it later.

Firefox 66.0.3 (64-bit)

**Comment by Moustachauve** [comment]
I think there is an issue with firefox itself. I added some code that will force the window to resize once the animation is done but it will not be 100% smooth. 

The fix should be released in the next version, which should be deployed in the next week.

**Comment by Moustachauve** [comment]
The new version has been deployed to the different browsers store and is now available to download.
