### ISSUE TITLE
Export All Cookies Buttons Not Working – Possibly due to JS Exception

### ISSUE THREAD

**Issue by alexduncan** [Moustachauve/cookie-editor#168]
**Browser:** Google Chrome
**Version:** 121.0.6167.184 (Official Build) (arm64)
**Extension Version:** 1.12.2

Nothing happens when I click either of these buttons:

<img width="555" alt="image" src="https://github.com/Moustachauve/cookie-editor/assets/710774/dc4369db-e1f3-4541-ba5c-9d7d4adecece">

And when I inspect the elements using the console I see the following JS exception:

<img width="981" alt="image" src="https://github.com/Moustachauve/cookie-editor/assets/710774/7edbb998-6a4b-410d-bf48-ea710796910f">

This is the code that is throwing the exception due to the element `#github-sponsor` not existing in the DOM.

<img width="909" alt="image" src="https://github.com/Moustachauve/cookie-editor/assets/710774/8cb0244b-fb7f-4726-83bb-94f58d499e86">

**Comment by Moustachauve** [comment]
Thanks for the report! This issue is already fixed in the development branch and will be fixed in the next version of Cookie-Editor.

I am hoping to get it out this week if all goes well.
