### ISSUE TITLE
Odd behavior from C-E.

### ISSUE THREAD

**Issue by Maxxxxxx** [Moustachauve/cookie-editor#170]
Firefox 122.01
Win 11

I used this in the past with no issues.
Now, whenever I click on the CE, I see this message: You do not have the permission required to read the cookies for this page.
Request permission for..."this site" or "all sites."

It throws me off.
What does this mean and why do I always get this message?

Thank you.

**Comment by Moustachauve** [comment]
This is for people who wants to be able to restrict which sites' cookies Cookie-Editor can access, for privacy reasons.

If you don't mind Cookie-Editor accessing all of your cookies, just select "All Sites" and accept. You should not get this message anymore after that.

**Comment by Maxxxxxx** [comment]
Christophe,

Should I mind?
Is it safe to share all?
I protect my privacy when reasonable.

Thank you.

N:L
________________________________

**Comment by Maxxxxxx** [comment]
Good job, then, Christophe,

I like this extension.

Thank you.

N:L
________________________________
