### ISSUE TITLE
can't edit cookies and save on Microsoft Edge 40.15063.674.0

### ISSUE THREAD

**Issue by renotesting** [Moustachauve/cookie-editor#18]
can't edit cookies and save on Microsoft Edge 40.15063.674.0

**Comment by Moustachauve** [comment]
I'll have to see if I can reproduce this issue. I don't think I have the same version of Edge installed and debugging in edge by itself is not the easiest thing to do.

**Comment by Moustachauve** [comment]
I will not be supporting the legacy edge browser
