### ISSUE TITLE
Opera extension has not yet been updated to 1.13

### ISSUE THREAD

**Issue by Elementari** [Moustachauve/cookie-editor#209]
Hello, I only wanted to mention that on the opera extension store, v. 1.13 has not yet been uploaded. Cheers.

**Comment by Moustachauve** [comment]
I'm sorry about that. Version 1.13 has been deployed to the Opera store on Feb 24, 2024 and has been awaiting moderation ever since. I don't think the Opera moderation team is very active.

![image](https://github.com/user-attachments/assets/e72b043a-37de-4c8a-bfb4-a2fcd29c2012)

**Comment by Elementari** [comment]
Perhaps it helps to remove it and upload a "fake" 1.13.0b" version?

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by Moustachauve** [comment]
1.13 has been published to the opera extension store today
