### ISSUE TITLE
Permission denied to set cookie

### ISSUE THREAD

**Issue by DarthBOR** [Moustachauve/cookie-editor#21]
Hey.

The subject message pops up when I insert cookies. Must be bug as well, for I do not see any permissions on the addon at all.

Regards.
![image](https://user-images.githubusercontent.com/9690833/69629674-2fa4d500-106e-11ea-8688-e7144e06fbea.png)

**Comment by Moustachauve** [comment]
Hello @DarthBOR , Sorry for the delay.

Did you activate any settings like "same site only" in chrome? Which site are you on when you get this?

**Comment by Moustachauve** [comment]
Hello @DarthBOR , sorry for the delay

Which site did you see this error on? 
Can you reproduce it on many sites? 
Were you trying to import cookie or create new cookies? 
Which browser were you using?

**Comment by DarthBOR** [comment]
Hey there. I was not using Chrome, it was Firefox. You can see the domain in the screenshot — it was google.com

**Comment by dele** [comment]
Also i have same problem on Firefox Portable.

**Comment by Sinbad-magi** [comment]
I'm facing this issue as well . I get the error notification in firefox . When i apply the same cookie in chrome , it doesn't get applied and there's no error notification too

**Comment by eletitos** [comment]
I have the same problems. 
In firefox I have the "permission denied to set cookie" and in chrome doesn't work either.

**Comment by tetious** [comment]
This seems to be an issue when setting third-party cookies. If you attempt to set a cookie for a domain that does not match your currently loaded page, you get the "permission denied" error in Firefox and "failed to parse or set" in Chrome.

Disabling third-party cookie blocking does not help in either browser.

**Comment by Moustachauve** [comment]
A new version was released on the Chrome Web Store (1.11.0). Can you check if this issue is still happening please?

**Comment by DarthBOR** [comment]
I can. But are there any plans to make Firefox version tho?

**Comment by Moustachauve** [comment]
Yes, it will be available soon for other browsers but is pending review for Firefox, Opera, Edge and Safari.

**Comment by Moustachauve** [comment]
Firefox version is now live!

**Comment by sonmalay** [comment]
![image](https://github.com/Moustachauve/cookie-editor/assets/140095005/9dc2ddd2-3f89-4455-bc38-b43346083438)
tôi không thể tải cookie trên máy tính của mình

**Comment by Moustachauve** [comment]
@sonmalay This seems to be an issue with Chrome or the Chrome Web Store directly and not with Cookie-Editor.

See https://support.google.com/chrome/answer/2898334 and please open a new ticket if you still experience this issue as it is irrelevant to the existing bug.

**Comment by yodaluca23** [comment]
Still happening when trying to export cookies from Chrome to Firefox

**Comment by aramessi** [comment]
still unable import it to firefox

**Comment by DevMaan707** [comment]
> still unable import it to firefox
> 

You can load by downgrading your firefox to older versions

**Comment by weskerty** [comment]
Try
https://github.com/weskerty/FirefoxCookieImport
