### ISSUE TITLE
Import not working in Chrome80.0.3987.100

### ISSUE THREAD

**Issue by Jay54520** [Moustachauve/cookie-editor#24]
Created cookies can be seen in 'Application-Storage-Cookies', but will be deleted after refreshing because the following request doesn't contain the cookies just set so the response will `set-cookie`.

**Comment by Moustachauve** [comment]
Hi @Jay54520 , I'm sorry you are having an issue.

I don't understand fully the issue. Can you give me some step to reproduce your issue please? 

Does it happen on every website?
Can you give me an example of cookie that disappear?

Thank you
