### ISSUE TITLE
Text foreground color in Firefox is honored, but background is not

### ISSUE THREAD

**Issue by cspiegel** [Moustachauve/cookie-editor#25]
This is Firefox 73.0 and Cookie Editor 1.9.0.

Problem:

For text in the Cookie Editor popup (when you click the extension button), the color is taken from the foreground color in Firefox's settings.  However, the background appears to be unconditionally white.  This caused a rather obvious issue when I had Firefox's text set to white on dark.

Steps to reproduce:

1. In Firefox's preferences, under "Language and Appearance", click "Colors"
2. Make the foreground text an obviously non-dark color (red is good)
3. Make the background black
3. Click on the Cookie Editor tool button

Note that all the text is red (or whatever color was selected), but the background is *not* dark.

**Comment by Moustachauve** [comment]
Thanks for reporting this issue, I'll be looking into it soon

**Comment by Moustachauve** [comment]
This will be fixed in the next version of cookie editor.
Sadly, I am not able to support custom colors properly.
Maybe someone can do a pull request one day with a proper fix if this is important for them.
