### ISSUE TITLE
Extension does not find cookies when "Site access" is set to "On click"

### ISSUE THREAD

**Issue by Rourke101** [Moustachauve/cookie-editor#26]
I have just installed Cookie Editor from:
https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm?hl=en

In any page, no matter which one, I get the message:
**_This page does not have any cookies_**
Which is false, as I can see them through the WDTools

If I try to add a cookie, I get a black bubble saying:
_**No host permissions for cookies at url: "https://www.google.com/search?.....".**_

Permissions-wide I have nothing special in my Windows computer, I am running an administrator.

**Comment by Rourke101** [comment]
I suppose it has something to do with this line:
`"permissions": [ "cookies", "\u003Call_urls>", "tabs", "storage" ],`

**Comment by Rourke101** [comment]
I found the issue:  I only allow extensions to work when I click on them. This way I prevent some security risks. However, the extension does not work when I had this option enabled. It only works when the extension can "read and change site data" on ALL sites. I think this is quite dangerous.

Would it be possible to adapt the extension so it acts on demand, i.e. when it is clicked?

**Comment by Moustachauve** [comment]
I'll look into it

**Comment by jesusrizo24** [comment]
Hello, I use the Cookie-editor extension as an alternative login method for my collaborators, on many pages they can enter correctly, but there are some platforms that simply do not allow entry through cookies. Is there any way to correct that problem?
In some of those error pages, the login via cookies is correct, but then it just doesn't work.
Thanks in advance.

**Comment by Moustachauve** [comment]
I believe adding the permission "activeTab" might fix this. It might even be possible that I can remove the "<all_urls>" permission with that change. That would greatly improve the security. I will experiment with this.

**Comment by Moustachauve** [comment]
@laboradite I'm sorry, this is not editthiscookie. This is the Cookie-Editor extension. You should give it a try.

**Comment by Moustachauve** [comment]
While the next version still won't support the "on click" permission only, there should be significant improvement. Permission will be able to be granted on a per site basis.

**Comment by Moustachauve** [comment]
A new permission system is in place in version 1.12.0! This version is slowly rolling out for all browsers.

This should allow you to only set access on some site for Cookie-Editor. Since this is the first version of this permission system, there might be some quirks. Please let me know in a new bug if you have any issues and I will fix them as soon as possible.
