### ISSUE TITLE
Unknow error

### ISSUE THREAD

**Issue by YassinIsVeryCool** [Moustachauve/cookie-editor#29]
Hello, when I try to import a cookie into Netflix, it automatically says "Unkown Error". I've tried with all browsers and still does it. Please fix this

**Comment by Moustachauve** [comment]
Hi, Thanks for the bug report. I'd need a little bit more information about this. Do you think you can share a sample of cookie with the sensitive information changed so I can see if I can reproduce this issue on my side?
