### ISSUE TITLE
Exporting google cookies

### ISSUE THREAD

**Issue by OllyHill** [Moustachauve/cookie-editor#33]
Hello Mate,

Was hoping to get some help on importing cookies for Firefox or Chrome. On both browsers, I've created new profiles and import the JSON cookies. I will occasionally get the permission denied error which, from reading your responses to other users, is because you can only import that cookie of the active website you're on. But, I am unable to import cookies for all google websites. I visit google.com and import by google cookies, but cannot access gmail still. Here's the steps to recreate the issue:

1) Create new profile in Chrome
2) Install extension from webstore
3) Go to google.com
4) Delete all cookies
5) Copy and paste JSON cookie into extension
6) Hit refresh and google.com shows account sign in upper right hand corner (changes to your icon with your name)
7) Click gmail in upper right corner and then you're prompted to sign in

Expected Behavior;
When clicking gmail, the user should be logged in and taken to their inbox.

What am I doing wrong?

Thanks for the help and appreciate the hard work.

Cheers, Olly

**Comment by Moustachauve** [comment]
Sadly, while I can't exactly tell you what step you are missing, this is not an issue with the extension. 

Google authentication is split across multiple domains and is quite complex, you might need to do more imports afterwards.
