### ISSUE TITLE
mysterious 'fakedomain.com' session cookie repeatedly set, apparently by cookie-editor

### ISSUE THREAD

**Issue by ginahoy** [Moustachauve/cookie-editor#35]
I've been troubleshooting an unknown session cookie from 'fakedomain.com'... After spending the past hour on this, I determined this cookie is somehow associated with cookie-editor. It automatically gets created when I open Chrome (my start page is set to the 'New Tab' page). If I delete the cookie, it will always be created again, although not necessarily immediately. If I disable cookie-editor, it will never be created. Here are the details: 

I'm guessing this some sort of development aid that should have been removed...?  I'm running v1.9.0 with Google Chrome v84.
```
Name
testSameSite
Content
someValue
Domain
fakedomain.com
Path
/
Send for
Same-site connections only
Accessible to script
Yes
Created
Sunday, August 9, 2020 at 10:28:25 PM
Expires
When the browsing session ends
```

**Comment by Moustachauve** [comment]
Hi @ginahoy 
Yes, you are correct, it is created by Cookie-Editor.
This is a cookie used to test if a browser supports the "same-site" attribute.
You can check the code here: https://github.com/Moustachauve/cookie-editor/blob/76f08de45c67eeb58c0f048060d317f494e090c5/interface/lib/browserDetector.js#L50

I agree that it could be done in a slightly more elegant way (create it once and remember the result), but it should not create any issues or any problems.

Let me know if you have other questions related to it

**Comment by ginahoy** [comment]
Thanks for confirming. No worries, I just needed to know it wasn't something nefarious!
