### ISSUE TITLE
How do I use cookie editor for Edge?

### ISSUE THREAD

**Issue by SlewedThread** [Moustachauve/cookie-editor#37]
Every time I open Cookie editor, it opens up Edge to Bing, but there is no option to edit it so I'm wondering where I can edit it. cookie editor works very well on Chrome and Firefox but I dont see the option for Edge. Please help. Thank you

**Comment by Moustachauve** [comment]
You can use it here:
https://microsoftedge.microsoft.com/addons/detail/cookieeditor/neaplmfkghagebokkhpjpoebhdledlfi
