### ISSUE TITLE
Doesn't work with Appmagic.rocks

### ISSUE THREAD

**Issue by jackhu9527** [Moustachauve/cookie-editor#39]
As is said in the Title, the extension seems to work for every other website, but I had no luck with this single website: Appmagic.rocks. Will really appreciate it if you can help fix this, if possible. Thanks for your hard work!

**Comment by Moustachauve** [comment]
Hello @jackhu9527, sorry for the delay. Are you still having this issue? It looks like the extension works for me

**Comment by jackhu9527** [comment]
Oh thanks for your response and no worries. I've found out later that it was caused by something else, and the extension works perfect. Thanks again and I wish you a great day.:)
