### ISSUE TITLE
Icons lacks tooltips and/or text. 

### ISSUE THREAD

**Issue by kplaczek** [Moustachauve/cookie-editor#4]
It would be nice to have tooltips of some sort to know what each button does and dont have to guess if i click this trash can icon then all the cookies will be deleted or just one. Maybe even text next to the icon on that bottom bar since there is so much unused space.

**Comment by Moustachauve** [comment]
Thank you for the feedback. This sound like a very good idea, I will definitely work on a solution for this

**Comment by kplaczek** [comment]
Fancy! Thanks.
