### ISSUE TITLE
Minor issue: test cookie cleanup

### ISSUE THREAD

**Issue by mhoye** [Moustachauve/cookie-editor#40]
In https://github.com/Moustachauve/cookie-editor/blob/76f08de45c67eeb58c0f048060d317f494e090c5/interface/lib/browserDetector.js#L49  

... cookie-editor doesn't clean up after itself, leaving its test key in place. It seems harmless enough, but you could consider changing this to the better known and IANA-supported  example.com and deleting the test key once you know the result of the test.

Thank you.

**Comment by Moustachauve** [comment]
Hi @mhoye, thanks for the feedback! I definitely plan to improve this

**Comment by Moustachauve** [comment]
This version is now available on the Chrome Web Store! It will be available soon but is pending review for Firefox, Opera, Edge and Safari.
