### ISSUE TITLE
Not supported on recent versions of Firefox for Android

### ISSUE THREAD

**Issue by rodiers** [Moustachauve/cookie-editor#41]
When I try to install the add-on it says: "Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. "

The probably cause is mentioned here: https://www.ghacks.net/2020/08/07/three-reasons-not-to-upgrade-to-the-new-firefox-for-android-browser-right-now/

**Comment by rodiers** [comment]
According to https://github.com/mozilla-mobile/fenix/issues/14034 the loading of all extensions should be possible on Firefox Nightly, but for the cookie-editor I still get the same message on Nightly.

**Comment by miraserver** [comment]
also ask this q....

**Comment by Olinere** [comment]
Same question. Can the author please add the newest version of Firefox? Because on his homepage there is a version for Android Firefox, and it does not work at all !

**Comment by Moustachauve** [comment]
I just tested the current version on Firefox nightly and it works. A iOS version is coming very soon. There is nothing more I can do until firefox releases a version that allows general extensions again or they select Cookie-Editor to run on all Android versions.
