### ISSUE TITLE
Firefox import issue

### ISSUE THREAD

**Issue by bintangf** [Moustachauve/cookie-editor#46]
i use firefox browser 83.0 (64-bit) with cookie editor 1.9.0 , in table "paste your json here" enter(newline) not detect and then i cant import my cookies because the cookie editor not detect json format.

**Comment by Goldmaster** [comment]
this is the same issue I'm facing as well. its due to firefox formatting the text along 1 line instead of leaving it as it is

**Comment by Soylent17** [comment]
I had this issue as well. It turned out the import doesn't like "sameSite": "unspecified". I replaced instances of this with "sameSite": "lax" and everything imported fine.

**Comment by Moustachauve** [comment]
Hi guys, sorry for the delay. I believe the most recent update I just deployed this week should have fixed this. If not, feel free to reopen this issue
