### ISSUE TITLE
Support for Safari browser

### ISSUE THREAD

**Issue by jayluxferro** [Moustachauve/cookie-editor#48]
I just realised the extension hasn't been deployed for Safari browser. I have ported it to Safari using web extensions. https://github.com/jayluxferro/Cookie-Editor. You can consider that in your next commit. 

Thanks for the good work.

**Comment by tomy0000000** [comment]
Thumbs up for this, hope we'll be able to download this on app store soon.

**Comment by jayluxferro** [comment]
Yeah very soon. I have to work on it further. Import not working.

**Comment by Moustachauve** [comment]
Hi, sadly since I do not make any profit from this extension and making extensions available in safari is very expensive, I can not afford making it available for Safari.
