### ISSUE TITLE
[Cookie-Editor] Import Button Isn't Working

### ISSUE THREAD

**Issue by Demoxing** [Moustachauve/cookie-editor#50]
The Import button straight-up doesn't work in firefox. It just doesn't do anything when I click on import. Please help me.

https://user-images.githubusercontent.com/53024273/102682186-a36fcd80-41ed-11eb-8ceb-a09342ecaf47.mp4

**Comment by DineshSolanki** [comment]
same for me.

**Comment by DineshSolanki** [comment]
Duplicate of #46

**Comment by ZacharyJo** [comment]
....

**Comment by Soylent17** [comment]
I had this issue as well.  It turned out the import doesn't like  "sameSite": "unspecified".  I replaced instances of this with "sameSite": "lax" and everything imported fine.

**Comment by Moustachauve** [comment]
I believe with the most recent version I deployed this week, this bug should be fixed, can you guys confirm that your issue is fixed please? Thank you!

**Comment by DineshSolanki** [comment]
thank you @Moustachauve , It's working now.

**Comment by Moustachauve** [comment]
Awesome, thank you! Sorry for the long time it took for me to update the extension.

**Comment by r3kashi** [comment]
The Import button straight-up doesn't work in firefox. It just doesn't do anything when I click on import. Please help me
