### ISSUE TITLE
Not working with Chrome

### ISSUE THREAD

**Issue by niharbd** [Moustachauve/cookie-editor#51]
Not working with Chrome. Error:
This site can’t be reachedThe webpage at https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

Requesting your urgent help to resolved the issue.
![Capture](https://user-images.githubusercontent.com/76545457/103854788-7f602780-50db-11eb-8a37-5e6f3999b056.PNG)

**Comment by Moustachauve** [comment]
hi @niharbd, I think this is a networking issue on your side.
