### ISSUE TITLE
Import cookie for another website?

### ISSUE THREAD

**Issue by mbaletic** [Moustachauve/cookie-editor#54]
Hi,

I've been trying to import cookies, but this tool seems to be "tab-based".
I'm wondering, is it possible to inject cookies for another website, one that isn't opened currently?

Thanks.

**Comment by mbaletic** [comment]
@Moustachauve 
Anything?

**Comment by Moustachauve** [comment]
Hi @mbaletic , sorry for the delay. Sadly, at this moment, I do not plan on allowing editing cookies of other website than the one in the current tab. Maybe in the future I might add a page that you can write an URL and see/edit the cookies for that url, but it is not planned yet.
