### ISSUE TITLE
Remove unneeded reference of facebook.com from devtool panel

### ISSUE THREAD

**Issue by dheri** [Moustachauve/cookie-editor#55]
[This line ](https://github.com/Moustachauve/cookie-editor/blob/master/interface/popup-android/cookie-list.html#L16) is unnecessarily referencing `facebook.com` in devtools panel. 

Screenshot of UI
![image](https://user-images.githubusercontent.com/24783071/113610198-ca2a0680-961a-11eb-8ea7-266cee1a18f3.png)

**Comment by Moustachauve** [comment]
@dheri  you are totally right, this was a leftover from testing that should not have been left there. I will remove it asap from the source code
