### ISSUE TITLE
Are the cookies extracted from each program in Chrome and Firefox compatible with each other?

### ISSUE THREAD

**Issue by EDD1802** [Moustachauve/cookie-editor#56]
HI! The program is really convenient to use and thank you for your hard work.
As I used it, I discovered that the format of the cookies extracted from the extensions of the two browsers are different.
Wouldn't this be a problem when crossing over to each other?
At first glance, Those are something looks quite different.
I think the Firefox format with the 'name' at the top was more comfortable to look at.

Is this just extracting cookie values that are the same as each other, with different Sequence?
But what I found was that when I imported a specific cookie value extracted from Chrome into Firefox as it was,

Chrome : "expirationDate": 1618609921.66361, 
Firefox : "expirationDate": 1618609921,

Chrome : "sameSite": null, 
Firefox : "sameSite": "no_restriction",

Chrome : None (There were no "firstPartyDomain' value)
Firefox : "firstPartyDomain": "",

There have been these changes. 
Why do these differences arise and are integrity guaranteed, okay to across??
This change was not found when moving cookies from the same browser extension.

**Comment by Moustachauve** [comment]
Yes, I also discovered while creating this extension that different browsers handle cookies slightly differently. 

The export will export it the way the browser used represent the data to be sure to keep as much data as possible in the most exact way. 

On import, if its the same type of browser used (ex, firefox to firefox) then everything should work fine.
If different browsers were used (ex, firefox to chrome) the extension will detect that some fields are not the perfect format and will convert whatever needs to be changed to be compatible.

While the conversion is not 100% lossless, there should not be any problem moving cookies between browser, most of these difference are browser specific behavior. 

Let me know if you have any issues with the conversions
