### ISSUE TITLE
Cookie Question

### ISSUE THREAD

**Issue by deehill** [Moustachauve/cookie-editor#62]
Hi  Christophe,

I'm trying to figure out how to solve an issue. 

If I have a browser with multiple Tabs, and the tabs are running different URLs/pages but the urls have the same domain "www.foo.com".

Is it possible to create the logic to copy the "cookie" from TAB1/URL1 to TAB2? Basically I'm testing running a number of different urls across the tabs, and I''m trying to figure out how to have an extension/logic that I can use/select that will take the cookie from TAB1 and apply it to the other TABs when I manually invoke the underlying logic in the extension.

I've scanned some of the logic of the cookie-editor extension and wondered if this logic could be developed via the app?

thoughts/comments?

thanks

-bruce

**Comment by Moustachauve** [comment]
Hi Bruce,

Sadly, I do not plan to implement any such feature for now. I'll let you know if I ever implement something like this!
