### ISSUE TITLE
Doesn't work with Kiwi browser on android.

### ISSUE THREAD

**Issue by Digital-XxX** [Moustachauve/cookie-editor#67]
I badly needed the extension but it doesn't work on Kiwi. I hope you consider changeing the layout.

**Comment by YandLiu** [comment]
In my case, this extension worked fine before, but after recent kiwi browser updates it doens't work well anymore.

**Comment by Charliewonders** [comment]
![Screenshot_20220609-122612](https://user-images.githubusercontent.com/107188432/172838272-a4df6f66-69ab-442c-af86-d02d1f153166.png)




This is the issue I'm having with this cookie editor

**Comment by Digital-XxX** [comment]
> ![Screenshot_20220609-122612](https://user-images.githubusercontent.com/107188432/172838272-a4df6f66-69ab-442c-af86-d02d1f153166.png)
> 
> This is the issue I'm having with this cookie editor

Uncheck the 'Hide annoying ads'

**Comment by YandLiu** [comment]
> > ![Screenshot_20220609-122612](https://user-images.githubusercontent.com/107188432/172838272-a4df6f66-69ab-442c-af86-d02d1f153166.png)
> > This is the issue I'm having with this cookie editor
> 
> Uncheck the 'Hide annoying ads'

I didn't check that, but it still didn't work.

**Comment by Moustachauve** [comment]
A new version that fixes this is now available on the Chrome Web Store! It will be available soon but is pending review for Firefox, Opera, Edge and Safari.
