### ISSUE TITLE
Does not work properly in Chrome with Icognito Mode

### ISSUE THREAD

**Issue by HeIp** [Moustachauve/cookie-editor#68]
Cookie Editor plugin does not work as intended in incognito mode

**Comment by Moustachauve** [comment]
What error are you getting? Did you enable the extension to run in incognito mode?

Here's how to allow an extension to run in incognito
- Open Incognito window
- Go to chrome://extensions
- Find the extension, click Details
- Toggle the button "Allow in Incognito" to allow the extension to run in incognito mode

**Comment by tienanhemho** [comment]
it shows cookies from default chrome profile

**Comment by Moustachauve** [comment]
Fixed by #89, will be part of a near future update
