### ISSUE TITLE
Cookie protector

### ISSUE THREAD

**Issue by McKinleyGroup** [Moustachauve/cookie-editor#7]
I would love a feature you could call "Cookie protector"...
This way I could:

1) protect a couple of cookies I need ("protected cookie")

2) erase all other cookies and still keep my "protected cookies"

That would be a really useful feature... because what the point of otherwise having to go through hundreds or even thousands of cookies?

Thank you for considering this feature for the "Moustachauve/cookie-editor"

**Comment by Moustachauve** [comment]
Thanks for the suggestion.

When do you expect cookies that are not protected to be deleted? Should it be when the user leave a website or those cookies should be fully blocked from being created entirely?

**Comment by McKinleyGroup** [comment]
@Moustachauve 

There should be an option to delete them when:
- when the user leaves a website
or 
- fully blocked from being created entirely

Both options make sense, so it should be up to the user to pick the desired option!

Thank you so much! :-)

**Comment by Moustachauve** [comment]
Thank you for the suggestion, @McKinleyGroup. I will definitely work on this in the future, but since I have a tight schedule, it may not be quite soon.

**Comment by Moustachauve** [comment]
No current plans to work on this in the future, sorry
