### ISSUE TITLE
Feature !! suggestion plz

### ISSUE THREAD

**Issue by 9-kl** [Moustachauve/cookie-editor#70]
I want to download a specific cookie to a textfile on update / when that cookie changes.

                        cookie name    |   domain   |     value
For example    
                          example    |     foo.com       |   1234

... change something on website ...

                           example          foo.com          456
*trigger* 

        cookie      saved to    c:\place\example.txt

example.txt   ==  "456"

this feature would be super awesome to have , im making my own program that needs this cookie auto downloading feature and i have no idea how i would do it myself .           im also new to git , and can only make .net programs :(
plshalp

**Comment by Moustachauve** [comment]
Hey @9-kl

Sadly, I am not looking into implementing such feature any time soon. I'll let you know if I get around to work on this in the future.

Thanks for the suggestion
