### ISSUE TITLE
"Unknown Error"

### ISSUE THREAD

**Issue by BrokenThe3rd** [Moustachauve/cookie-editor#71]
After Using the extension for a couple days i just get "unknown error" every time i import any cookies

**Comment by burning-wolf** [comment]
same to me too

**Comment by Moustachauve** [comment]
Is your tab open to the same domain that you are importing your cookies from?

**Comment by burning-wolf** [comment]
yes

**Comment by Moustachauve** [comment]
@burning-wolf would you feel comfortable providing me with an anonymized  version of the cookies you are trying to import that fails to help me reproduce the error?

**Comment by burning-wolf** [comment]
sure 
[cookies.txt](https://github.com/Moustachauve/cookie-editor/files/8313007/cookies.txt)
i attached a txt file containing cookies pls try to apply them at envato.com

**Comment by Moustachauve** [comment]
@burning-wolf 
If you are on www.envato.com, it is expected that the cookies with domain set to ".elements.envato.com" will fail since you are not directly on the same domain

I get the permission denied on www.envato.com but everything works as expected if I import the same cookies from elements.envato.com

**Comment by burning-wolf** [comment]
yeah i think i mentioned the link incorrectly i tried again importing in elements.envato.com but its still showing unknown error popup three times

**Comment by HeartsofCourse** [comment]
I'm having the same exact problem, but with Netflix.com. The thing is, these same exact cookies worked on the same exact site just a few days ago
