### ISSUE TITLE
Got cookie from Chrome that failed to import in Firefox

### ISSUE THREAD

**Issue by ruperson** [Moustachauve/cookie-editor#74]
Figured out that field in my cookoe json "sameSite": "None" makes import button fail to proceed import,
Maybe somehow related with #56

**Comment by Nafiu56** [comment]
I cannot export cookies editor cord

**Comment by Nafiu56** [comment]
I don’t have access to long in to the cookie editor

**Comment by Moustachauve** [comment]
Duplicate of #56
