### ISSUE TITLE
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by yeyuchen198** [Moustachauve/cookie-editor#76]
(Issue with Chrome browser, and "manifest_version": 3)

I got an error on the file -> interface\devtools\devtoolCookieHandler.js

in line 95, where is "sendMessage("getCurrentTab", null, function (tabInfo) {...}"
I find the tabInfo is undefined. 

The error is "Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.".

See "This is a change in chromes behavior since 72 I guess. The problem is if you try to call chrome.runtime.connect() before you have opened a channel on the other end in Background or popup page then you will get that error."
 on the page https://stackoverflow.com/questions/54181734/chrome-extension-message-passing-unchecked-runtime-lasterror-could-not-establi/54686484#54686484

It works when  the "manifest_version" is 2, but does not on 3.

But Manifest version 2 is deprecated, and support will be removed in 2023.

**Comment by Moustachauve** [comment]
Hey! I believe this should be fix in commit https://github.com/Moustachauve/cookie-editor/commit/6033ce9e3504f8b0baebaa47dfb99a50d7a71887 with ticket #90
