### ISSUE TITLE
Cookies not being saved in Firefox

### ISSUE THREAD

**Issue by sean20222** [Moustachauve/cookie-editor#77]
Hi, I'm having issues with my cookies not being saved into Firefox browser.  I'll manually import the cookies but once I close the browser and reopen it to visit the same site...those same cookies that I imported aren't being saved.  Does anyone have any insight as to why this is? Thanks in advance!

**Comment by Moustachauve** [comment]
Are your cookies that you are importing set as "session" only? Do they have an expiration date?
