### ISSUE TITLE
button tags for blind users

### ISSUE THREAD

**Issue by sativarg-tuta** [Moustachauve/cookie-editor#79]
Dear Moustachauve,
### Hello, I am blind and new to github as a blind user... I am new to cookie editor as well some of the buttons are graphical without tags or words Please help?
Please consider supplying words to the buttons so blind users can use them
Please consider more documentation that is text based to descriptions and documentation as well.
thank you
chuck 🔥💖🔥

**Comment by Moustachauve** [comment]
Hello sativarg-tuta,

You bring excellent points. Cookie-Editor should definitely be more accessible. I will try to work on this as my priority number one. 

Thank you!

**Comment by sativarg-tuta** [comment]
Thank you very much. Moustachauve, your professionalism and diligence is refreshing. I am replying all as apposed to simply replying... I do not see a list of recipients though. Hope that is OK.... Now I can find out why Hcapture accessability cookie is not working on eBay's nasty sign security check... thank you so much
blessings
chuck 🔥💖🔥

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Apr 27, 2022, 8:54 PM by ***@***.***:

**Comment by Moustachauve** [comment]
A new version that should improve accessibility is now available on the Chrome Web Store! It will be available soon but is pending review for Firefox, Opera, Edge and Safari.

I would greatly appreciate any feedback to make it better and more accessible!

**Comment by sativarg-tuta** [comment]
Hi Christophe Gagnier and or Moustachauve, 
Thank you for your work. To be honest I have not used cookie editor for quite a while now. There was one specific thing I was trying to see... some sort of setting in a cookie I wanted to set. I can not remember what that was. OK old man issues... LOL
When the upgrade comes out for Firefox I will try it out. Now that I remember the editor is way more than just an editor it is a sort of interpreter too. I would like to wade through the cookies I am whitelisting so I can see just what is in there.
thanks for your hard work
blessings
chuck 🔥💖🔥
