### ISSUE TITLE
Hide 'Cookie Editor' tab in Chrome DevTools

### ISSUE THREAD

**Issue by ziishaned** [Moustachauve/cookie-editor#91]
Is it possible to hide Cookie Editor from the chrome developer tools?
![CleanShot 2022-06-28 at 20 29 33@2x](https://user-images.githubusercontent.com/16267321/176232373-64cf8ed2-314f-4824-82e8-2ec296b7cbda.png)

**Comment by Moustachauve** [comment]
This could be added as an option, I'd have to check how to add global configuration for extensions

**Comment by Moustachauve** [comment]
This is now fixed in version 1.12.0. You will find an option to turn off de tools in the Options page.

This version is slowly rolling out for all browsers.
