### ISSUE TITLE
Unknown Error  Import  Cookies on Chrome

### ISSUE THREAD

**Issue by MarceloWort** [Moustachauve/cookie-editor#92]
I'm importing cookies from my profile of Chrome and Facebook and Gmail, from one machine to another, but, every time appears "unknown error" after I copy the Cookie and click import.   Sometime works, sometime not works and i try several times.   Some time I can enter in Facebook, some time can´t enter in GMAIL.    Someone know what is the problem and how can I solve ??    Thanks

**Comment by Moustachauve** [comment]
Next version coming out soon will fix this.
