### ISSUE TITLE
importing cookies does not work on brave browser

### ISSUE THREAD

**Issue by Gooferball69** [Moustachauve/cookie-editor#99]
I was trying to import Grammarly.com cookies on brave but it doesn't work. It does delete, but when I go to import cookies and paste the json, it goes to the list and nothing appears but has a black lil text box with unknown error multiple times.

I turned off any conflicting add blockers with it too on brave.

but when I did it with chrome with the same extensions the importing works.

**Comment by aadivyaraushan** [comment]
Just experienced this same issue. It started quite recently. This wasn't an issue a week ago.

**Comment by stout-cob** [comment]
can confirm this issue with Brave

**Comment by Moustachauve** [comment]
Next version coming out soon will fix this.
